server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: springdemo
    database: h2
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
springdoc:
  api-docs:
    path: /v3/api-docs  # Default API docs path
  swagger-ui:
    path: /swagger-ui.html
    config-url: http://localhost:8081/v3/api-docs
#  swagger-ui.config-url: classpath:/META-INF/rest-application.json