server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        default_schema: SPRINGDEMO
    database: h2
    defer-datasource-initialization: true


